import { Ubuntu } from "next/font/google"; // font of this project
import "./globals.css";
import { cn } from "@/lib/utils";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";
import Navbar from "@/components/layouts/Navbar";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "h-full font-sans antialiased bg-background",
          ubuntu.className
        )}
      >
        <MaxWidthWrapper >
          <Navbar/>
          <main className="flex flex-col min-h-screen">
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </MaxWidthWrapper>
      </body>
    </html>
  );
}
